# Generated by Django 5.1.7 on 2025-04-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('interventions', '0001_initial'),
        ('stock', '0002_article_remove_livraison_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='clients.client'),
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='panne',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='intervention',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='interventions.vehicule'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant_main_oeuvre', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('impayee', 'Imppayée')], default='impayee', max_length=50)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='interventions.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='LignePanne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_pannes', to='interventions.intervention')),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_pannes', to='interventions.panne')),
            ],
        ),
        migrations.CreateModel(
            name='MaterielUtilise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField()),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_utilises', to='interventions.intervention')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='stock.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
