# Generated by Django 5.1.7 on 2025-04-30 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_alter_vehicule_client_remove_intervention_panne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='date_signalement',
        ),
        migrations.AddField(
            model_name='lignepanne',
            name='date_signalement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignepanne',
            name='description',
            field=models.TextField(default='Pas de description'),
            preserve_default=False,
        ),
    ]
