# Generated by Django 5.1.7 on 2025-04-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_remove_panne_date_signalement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='nom',
            field=models.CharField(default='non defini', max_length=100),
            preserve_default=False,
        ),
    ]
