# Generated by Django 4.2.18 on 2025-03-26 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(choices=[('Mécanicien', 'Mécanicien'), ('Réceptionniste', 'Réceptionniste'), ('Comptable', 'Comptable'), ('Chef d’atelier', 'Chef d’atelier')], max_length=50)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_embauche', models.DateField()),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Suspendu', 'Suspendu'), ('Licencié', 'Licencié')], default='Actif', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources_humaine.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=20)),
                ('annee', models.IntegerField()),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources_humaine.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Résilié', 'Résilié')], max_length=50)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources_humaine.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=50)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources_humaine.employe')),
            ],
        ),
    ]
