# Generated by Django 5.1.7 on 2025-04-02 14:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources_humaine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CD', unique=True),
        ),
    ]
