# Generated by Django 5.1.7 on 2025-04-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_username_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gerant', 'Gérant'), ('receptionniste', 'Réceptionniste'), ('comptable', 'Comptable'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
