# Generated by Django 5.1.7 on 2025-04-17 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tresorerie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('entree', 'Entrée de fonds'), ('sortie', 'Sortie de fonds')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
